# 1. What are the different data structures used in Tensorflow?. Give some examples

TensorFlow, an open-source machine learning library, uses various data structures to represent and manipulate data efficiently. Here are some of the key data structures used in TensorFlow:

1. **Tensors:**
   - Tensors are the fundamental building blocks in TensorFlow, representing multi-dimensional arrays or matrices. They can have any number of dimensions (rank) and are the primary data structure for storing input data, weights, and activations.
   - Example:

In [2]:
import tensorflow as tf
tensor_1d = tf.constant([1, 2, 3])
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])

2. **Constants:**
   - Constants are tensors with fixed values that do not change during the execution of a program. They are often used for storing hyperparameters or fixed input values.
   - Example:



In [4]:
import tensorflow as tf
constant_tensor = tf.constant([1, 2, 3])

3. **Variables:**
   - Variables are tensors whose values can be modified during the execution of a program. They are typically used to store model parameters that need to be updated during training.
   - Example:

In [5]:
import tensorflow as tf
variable_tensor = tf.Variable([1, 2, 3])

4. **Placeholders:**
   - Placeholders are used to feed actual data into a TensorFlow computational graph during runtime. They are often used for input data in training.
   - Example:


In [10]:
import tensorflow as tf

# Using tf.keras.Input for placeholder-like behavior
x = tf.keras.Input(shape=(10,))


5. **Sparse Tensors:**
   - Sparse tensors are used to efficiently represent tensors with a large number of zero values. They are particularly useful in scenarios where most elements are zero.

In [7]:
import tensorflow as tf
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 1]], values=[1, 2], dense_shape=[2, 2])

6. **Ragged Tensors:**
   - Ragged tensors represent tensors with non-uniform shapes along one or more dimensions. They are useful for sequences or nested data where the length of each element can vary.
   - Example:

In [8]:
import tensorflow as tf
ragged_tensor = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])

7. **Eager Tensors:**
   - Eager tensors are used in TensorFlow Eager Execution, allowing for immediate evaluation of operations. In Eager mode, TensorFlow operations are executed eagerly like regular Python code.
   - Example:

In [9]:
import tensorflow as tf
tf.config.run_functions_eagerly(True)  # Enable Eager Execution
eager_tensor = tf.constant([1, 2, 3])

# 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example

In TensorFlow, both constants and variables are used to represent tensors, but they have different characteristics.

1. **TensorFlow Constants:**
   - Constants are tensors whose values cannot be changed after initialization.
   - They are created using the `tf.constant` function.
   - Once a constant is defined, its value remains the same throughout the execution of a TensorFlow program.


In [11]:
import tensorflow as tf

# Creating a TensorFlow constant
a = tf.constant([2.0, 3.0, 4.0], dtype=tf.float32)

# Trying to assign a new value to the constant will result in an error
# a = a + 1  # This line will raise an error


2. **TensorFlow Variables:**
   - Variables are used to represent trainable parameters in a model.
   - They are created using the `tf.Variable` class.
   - The values of variables can be changed during the execution of a TensorFlow program, making them suitable for storing and updating model parameters during training.

In [12]:
import tensorflow as tf

# Creating a TensorFlow variable
b = tf.Variable([2.0, 3.0, 4.0], dtype=tf.float32)

# Updating the value of the variable
b.assign([5.0, 6.0, 7.0])

# Variables can be used in mathematical operations and can be updated
b = b + 1.0

# 3.Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow

TensorFlow provides functions and operators for performing various matrix operations, including addition, multiplication, and element-wise operations. Here's an overview of these operations:

### Matrix Addition:

Matrix addition is performed element-wise, and the matrices must have the same dimensions.


### Matrix Multiplication:

Matrix multiplication is performed using the `tf.matmul` function or the `@` operator. The number of columns in the first matrix must be equal to the number of rows in the second matrix.


### Element-wise Operations:

Element-wise operations are performed on corresponding elements of two matrices or a matrix and a scalar.


In [13]:
import tensorflow as tf

# Define two matrices
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Matrix addition
C = tf.add(A, B)

# Alternatively, you can use the '+' operator
C_alternative = A + B

# Print the result
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix C (Sum):\n", C)
print("Matrix C (Alternative):\n", C_alternative)


Matrix A:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Matrix B:
 tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)
Matrix C (Sum):
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Matrix C (Alternative):
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)


In [15]:
# Define two matrices
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Matrix multiplication
D = tf.matmul(A, B)

# Alternatively, you can use the '@' operator
D_alternative = A @ B

# Print the result
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix D (Product):\n", D)
print("Matrix D (Alternative):\n", D_alternative)


Matrix A:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Matrix B:
 tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)
Matrix D (Product):
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
Matrix D (Alternative):
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [14]:
# Define a matrix and a scalar
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
scalar = 2.0

# Element-wise addition with a scalar
E_add_scalar = tf.add(A, scalar)

# Element-wise multiplication with a scalar
E_multiply_scalar = tf.multiply(A, scalar)

# Print the results
print("Matrix A:\n", A)
print("Element-wise Addition with Scalar:\n", E_add_scalar)
print("Element-wise Multiplication with Scalar:\n", E_multiply_scalar)


Matrix A:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Element-wise Addition with Scalar:
 tf.Tensor(
[[3. 4.]
 [5. 6.]], shape=(2, 2), dtype=float32)
Element-wise Multiplication with Scalar:
 tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)


## Part 2: Practical Implementation 
## Task 1: Creating and Manipulating Matrice

## 1.Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A

In [37]:
import tensorflow as tf

# Create a 3x3 matrix with random normal values
A = tf.random.normal(shape=(3, 3), mean=0, stddev=1, dtype=tf.float32)

# Display the values of matrix A
print("Matrix A:\n", A.numpy())


Matrix A:
 [[ 0.10513849  0.9730392  -0.80379575]
 [-1.2557931   0.5607763   0.67032516]
 [ 1.1329962   0.08792424 -1.0428816 ]]


# 2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B

In [38]:
import tensorflow as tf

# Create a 4x4 matrix with truncated normal values
B = tf.random.truncated_normal(shape=(3, 3), mean=0, stddev=1, dtype=tf.float32)

# Display the values of matrix B
print("Matrix B:\n", B.numpy())


Matrix B:
 [[-0.2663034  -1.9332291   1.7789391 ]
 [-0.49818808  1.2810495   0.2453327 ]
 [ 0.7400403  -0.54525626 -0.25681627]]


# 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C

In [39]:
import tensorflow as tf

# Create a 2x2 matrix with normal distribution values
mean_value = 3
stddev_value = 0.5
C = tf.random.normal(shape=(3, 2), mean=3, stddev=0.5, dtype=tf.float32)

# Display the values of matrix C
print("Matrix C:\n", C.numpy())


Matrix C:
 [[3.542968  3.417956 ]
 [3.0315757 2.6875625]
 [2.023169  3.1942003]]


# 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D 

In [40]:
import tensorflow as tf

# Perform matrix addition
D = tf.add(A, B)

# Display the values of matrices A, B, and D
print("Matrix A:\n", A.numpy())
print("\nMatrix B:\n", B.numpy())
print("\nMatrix D (Result of Addition):\n", D.numpy())


Matrix A:
 [[ 0.10513849  0.9730392  -0.80379575]
 [-1.2557931   0.5607763   0.67032516]
 [ 1.1329962   0.08792424 -1.0428816 ]]

Matrix B:
 [[-0.2663034  -1.9332291   1.7789391 ]
 [-0.49818808  1.2810495   0.2453327 ]
 [ 0.7400403  -0.54525626 -0.25681627]]

Matrix D (Result of Addition):
 [[-0.16116491 -0.9601899   0.9751434 ]
 [-1.7539811   1.8418257   0.9156579 ]
 [ 1.8730365  -0.45733202 -1.2996979 ]]


# 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [41]:
# Perform matrix multiplication
E = tf.matmul(D, C)

# Display the values of matrices C and E
print("Matrix C:\n", C.numpy())
print("Matrix E:\n", E.numpy())


Matrix C:
 [[3.542968  3.417956 ]
 [3.0315757 2.6875625]
 [2.023169  3.1942003]]
Matrix E:
 [[-1.5090106  -0.01662167]
 [ 1.2218655   1.8797859 ]
 [ 2.6201634   1.0213529 ]]


# Task 2: Performing Additional Matrix Operation 
# 1.Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function

In [42]:
import tensorflow as tf

# Define matrix F with dimensions 3x3
F = tf.random.uniform(shape=(3, 3), minval=0, maxval=1, dtype=tf.float32)

# Display the values of matrix F
print("Matrix F:\n", F.numpy())


Matrix F:
 [[0.17038596 0.03125179 0.07138896]
 [0.12079787 0.35857928 0.31019437]
 [0.5420991  0.77410746 0.94472086]]


# 2. Calculate the transpose of matrix F and store the result in matrix G

In [43]:
# Calculate the transpose of matrix F
G = tf.transpose(F)

# Display the values of matrices F and G
print("Matrix F:\n", F.numpy())
print("\nMatrix G (Transpose of F):\n", G.numpy())


Matrix F:
 [[0.17038596 0.03125179 0.07138896]
 [0.12079787 0.35857928 0.31019437]
 [0.5420991  0.77410746 0.94472086]]

Matrix G (Transpose of F):
 [[0.17038596 0.12079787 0.5420991 ]
 [0.03125179 0.35857928 0.77410746]
 [0.07138896 0.31019437 0.94472086]]


# 3. Calculate the element-wise exponential of matrix F and store the result in matrix H

In [44]:
# Calculate the element-wise exponential of matrix F
H = tf.exp(F)

# Display the values of matrices F and H
print("Matrix F:\n", F.numpy())
print("\nMatrix H (Element-wise Exponential of F):\n", H.numpy())


Matrix F:
 [[0.17038596 0.03125179 0.07138896]
 [0.12079787 0.35857928 0.31019437]
 [0.5420991  0.77410746 0.94472086]]

Matrix H (Element-wise Exponential of F):
 [[1.1857624 1.0317452 1.0739989]
 [1.1283967 1.4312944 1.3636901]
 [1.7196127 2.1686556 2.5720954]]


# 4. Create a matrix I by concatenating matrix F and matrix G horizontally

In [45]:
# Concatenate matrices F and G horizontally
I = tf.concat([F, G], axis=1)

# Display the values of matrices F, G, and I
print("Matrix F:\n", F.numpy())
print("\nMatrix G:\n", G.numpy())
print("\nMatrix I (Concatenation of F and G horizontally):\n", I.numpy())


Matrix F:
 [[0.17038596 0.03125179 0.07138896]
 [0.12079787 0.35857928 0.31019437]
 [0.5420991  0.77410746 0.94472086]]

Matrix G:
 [[0.17038596 0.12079787 0.5420991 ]
 [0.03125179 0.35857928 0.77410746]
 [0.07138896 0.31019437 0.94472086]]

Matrix I (Concatenation of F and G horizontally):
 [[0.17038596 0.03125179 0.07138896 0.17038596 0.12079787 0.5420991 ]
 [0.12079787 0.35857928 0.31019437 0.03125179 0.35857928 0.77410746]
 [0.5420991  0.77410746 0.94472086 0.07138896 0.31019437 0.94472086]]


# 5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [46]:
# Concatenate matrices F and H vertically
J = tf.concat([F, H], axis=0)

# Display the values of matrices F, H, and J
print("Matrix F:\n", F.numpy())
print("\nMatrix H:\n", H.numpy())
print("\nMatrix J (Concatenation of F and H vertically):\n", J.numpy())


Matrix F:
 [[0.17038596 0.03125179 0.07138896]
 [0.12079787 0.35857928 0.31019437]
 [0.5420991  0.77410746 0.94472086]]

Matrix H:
 [[1.1857624 1.0317452 1.0739989]
 [1.1283967 1.4312944 1.3636901]
 [1.7196127 2.1686556 2.5720954]]

Matrix J (Concatenation of F and H vertically):
 [[0.17038596 0.03125179 0.07138896]
 [0.12079787 0.35857928 0.31019437]
 [0.5420991  0.77410746 0.94472086]
 [1.1857624  1.0317452  1.0739989 ]
 [1.1283967  1.4312944  1.3636901 ]
 [1.7196127  2.1686556  2.5720954 ]]
